// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2u8hfpgBQo7CrSLm5JucxOaH6PX6GNA',
    appId: '1:707883093308:web:ef74389dee4a228f552239',
    messagingSenderId: '707883093308',
    projectId: 'pocia-f423a',
    authDomain: 'pocia-f423a.firebaseapp.com',
    storageBucket: 'pocia-f423a.firebasestorage.app',
    measurementId: 'G-8K18YBVPEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5VMkW5o1lYIjiMWWoj8yJpWgikYnKm8',
    appId: '1:707883093308:android:50ac1c76e2e6af6d552239',
    messagingSenderId: '707883093308',
    projectId: 'pocia-f423a',
    storageBucket: 'pocia-f423a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA7oxXll4kf9U5bcitQHU1WYsXmZsatm8',
    appId: '1:707883093308:ios:0547e6e95e3fa0b5552239',
    messagingSenderId: '707883093308',
    projectId: 'pocia-f423a',
    storageBucket: 'pocia-f423a.firebasestorage.app',
    iosBundleId: 'com.example.pocIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2u8hfpgBQo7CrSLm5JucxOaH6PX6GNA',
    appId: '1:707883093308:web:23643efeab585694552239',
    messagingSenderId: '707883093308',
    projectId: 'pocia-f423a',
    authDomain: 'pocia-f423a.firebaseapp.com',
    storageBucket: 'pocia-f423a.firebasestorage.app',
    measurementId: 'G-D6ZXLSL7EM',
  );
}
